import type { LessonContent } from "@/lib/lesson-content-types";

export const formsOfEnergyAndConservation: LessonContent = {
  subjectSlug: "physics", chapterSlug: "energy-basics", lessonSlug: "forms-of-energy-and-conservation", title: "Forms of Energy and Conservation",
  objectives: ["Identify common energy stores and transfers","Calculate kinetic and gravitational potential energy","Explain conservation of energy","Distinguish useful and wasted energy","Calculate efficiency","Compare renewable and non-renewable resources"],
  sections: [
    { kind:"overview", paragraphs:["A moving bicycle, a stretched spring, a hot drink and a charged battery all involve energy. Energy is the ability to cause change or do work.","Energy does not disappear when something slows down or cools. It is transferred between stores and often spreads into the surroundings."]},
    { kind:"callout", variant:"definition", title:"Energy", body:"Energy is measured in joules (J). It can be stored in different ways and transferred by forces, heating, electrical currents or radiation."},
    { kind:"cards", heading:"Common energy stores", columns:3, items:[
      {title:"Kinetic",icon:"activity",text:"Energy of moving objects."},{title:"Gravitational potential",icon:"arrow-up",text:"Energy due to position in a gravitational field."},{title:"Elastic potential",icon:"move",text:"Energy stored by stretching or compressing."},{title:"Chemical",icon:"flask-conical",text:"Energy stored in fuels, food and batteries."},{title:"Thermal",icon:"thermometer",text:"Energy associated with particle motion."},{title:"Nuclear",icon:"atom",text:"Energy stored in atomic nuclei."}
    ]},
    { kind:"theory", heading:"Energy transfers", paragraphs:["Energy can be transferred mechanically when a force moves an object, electrically when charges move, by heating, or by radiation such as light and sound.","A device normally has an intended useful transfer and other transfers that are less useful. These unwanted transfers often warm the surroundings or produce sound."], list:["Torch: chemical → electrical → light + thermal","Fan: electrical → kinetic + sound + thermal","Car: chemical → kinetic + thermal + sound","Solar panel: light → electrical + thermal"]},
    { kind:"energyExplorer", heading:"Interactive activity — Energy stores and transformations"},
    { kind:"theory", heading:"Kinetic energy", paragraphs:["Kinetic energy depends on mass and speed. Doubling the mass doubles kinetic energy, but doubling speed makes kinetic energy four times as large." ]},
    { kind:"formula", latex:"E_k=\\frac{1}{2}mv^2", caption:"$E_k$ in joules, $m$ in kilograms, $v$ in metres per second"},
    { kind:"example", prompt:"Find the kinetic energy of a 4 kg trolley moving at 3 m/s.", steps:["Write $E_k=\\\\frac12mv^2$.","Substitute $m=4$ kg and $v=3$ m/s.","$E_k=0.5\\\\times4\\\\times3^2$.","$E_k=18$ J."], answer:"Kinetic energy = 18 J."},
    { kind:"theory", heading:"Gravitational potential energy", paragraphs:["Lifting an object transfers energy to its gravitational potential store. Near Earth's surface, the increase depends on mass, gravitational field strength and vertical height." ]},
    { kind:"formula", latex:"E_p=mgh", caption:"$E_p$ in joules, $m$ in kg, $g\\approx9.8$ N/kg, $h$ in metres"},
    { kind:"example", prompt:"A 6 kg box is lifted vertically by 2.5 m. Calculate the gain in gravitational potential energy using g = 9.8 N/kg.", steps:["Write $E_p=mgh$.","Substitute $6\\\\times9.8\\\\times2.5$.","Calculate $E_p=147$ J."], answer:"GPE gained = 147 J."},
    { kind:"theory", heading:"Conservation of energy", paragraphs:["Energy cannot be created or destroyed. In a closed system, the total amount of energy remains constant, although it may move between stores.","A falling object loses gravitational potential energy and gains kinetic energy. Air resistance transfers some energy to thermal stores, so not all of it remains as mechanical energy." ]},
    { kind:"callout", variant:"remember", title:"Energy is not used up", body:"A device transfers energy. When we say energy is 'wasted', we mean it has spread into less useful stores, not that it has vanished."},
    { kind:"theory", heading:"Efficiency", paragraphs:["Efficiency compares useful output energy with total input energy. It can be written as a decimal or percentage and can never exceed 100%." ]},
    { kind:"formula", latex:"\\text{efficiency}=\\frac{\\text{useful energy output}}{\\text{total energy input}}\\times100\\%", caption:"Use the same energy unit for input and output"},
    { kind:"example", prompt:"A motor receives 800 J and transfers 600 J usefully. Find its efficiency.", steps:["Efficiency $=600/800\\\\times100\\\\%$.","$=0.75\\\\times100\\\\%$.","$=75\\\\%$."], answer:"Efficiency = 75%. The remaining 200 J is transferred to less useful stores."},
    { kind:"comparison", heading:"Energy resources", left:{title:"Renewable",items:["Solar, wind, hydroelectric, tidal, geothermal, biomass","Replenished naturally on a human timescale","Often lower operational greenhouse emissions","Can be intermittent or location-dependent"]}, right:{title:"Non-renewable",items:["Coal, oil, natural gas and nuclear fuels","Finite reserves","Fossil fuels release greenhouse gases","Often reliable and energy-dense"]}},
    { kind:"realWorld", heading:"Energy decisions in real life", items:[{area:"Homes",text:"Insulation reduces unwanted thermal energy transfer."},{area:"Transport",text:"Regenerative braking transfers kinetic energy back to a battery."},{area:"Power generation",text:"Engineers compare reliability, cost, emissions and environmental impact."},{area:"Appliances",text:"Efficiency labels help consumers compare useful output for the same input."}]},
    { kind:"classifyActivity", heading:"Activity — Identify the main energy store", categories:["Kinetic","Gravitational potential","Elastic potential","Chemical","Thermal"], items:[{term:"A moving train",category:"Kinetic"},{term:"A book on a high shelf",category:"Gravitational potential"},{term:"A stretched bow",category:"Elastic potential"},{term:"Fuel in a car",category:"Chemical"},{term:"A hot saucepan",category:"Thermal"}]},
    { kind:"mistakes", items:[{wrong:"Saying energy disappears because of friction.",right:"Friction transfers energy mainly to thermal stores in the objects and surroundings."},{wrong:"Using speed instead of speed squared in kinetic energy.",right:"Calculate $v^2$ before multiplying by $\\\\frac12m$."},{wrong:"Using horizontal distance for gravitational potential energy.",right:"Use the vertical height change."},{wrong:"Reporting efficiency above 100%.",right:"Check input and output values and use the same units."}]},
    { kind:"practice", heading:"Practice (not graded)", questions:[
      {prompt:"Which energy store does a moving car have?",options:["Kinetic","Chemical only","Gravitational only"],answer:0,explanation:"Motion gives the car kinetic energy."},
      {prompt:"A 2 kg object moves at 4 m/s. What is its kinetic energy?",options:["8 J","16 J","32 J"],answer:1,explanation:"$E_k=0.5\\\\times2\\\\times4^2=16$ J."},
      {prompt:"Which statement expresses conservation of energy?",options:["Energy is used up","Total energy remains constant in a closed system","Useful energy always increases"],answer:1,explanation:"Energy changes store or pathway but total energy is conserved."},
      {prompt:"A device gives 40 J useful output from 50 J input. Efficiency?",options:["20%","80%","125%"],answer:1,explanation:"$40/50\\\\times100=80\\\\%$."},
      {prompt:"Which is renewable?",options:["Coal","Wind","Natural gas"],answer:1,explanation:"Wind is naturally replenished."}
    ]},
    { kind:"summary", points:["Energy is measured in joules and exists in different stores.","Energy transfers mechanically, electrically, by heating or radiation.","Kinetic energy is $\\\\frac12mv^2$.","Gravitational potential energy change is $mgh$.","Total energy is conserved in a closed system.","Efficiency compares useful output with total input.","Renewable and non-renewable resources have different benefits and limitations."]},
    { kind:"gradedQuiz", heading:"Lesson Quiz: Forms of Energy and Conservation", passMark:60, questions:[
      {type:"mc",marks:1,prompt:"What is the SI unit of energy?",options:["watt","joule","newton","pascal"],answer:1,explanation:"Energy is measured in joules (J)."},
      {type:"mc",marks:2,prompt:"Find the kinetic energy of a 3 kg object moving at 4 m/s.",options:["6 J","12 J","24 J","48 J"],answer:2,explanation:"$E_k=0.5\\\\times3\\\\times4^2=24$ J."},
      {type:"mc",marks:2,prompt:"A 5 kg object is lifted 2 m. Using g = 10 N/kg, what GPE is gained?",options:["10 J","25 J","50 J","100 J"],answer:3,explanation:"$E_p=5\\\\times10\\\\times2=100$ J."},
      {type:"tf",marks:1,prompt:"Energy is destroyed when friction slows an object.",answer:false,explanation:"Friction transfers energy to thermal stores; energy is conserved."},
      {type:"mc",marks:2,prompt:"A lamp receives 200 J and produces 50 J of useful light. What is its efficiency?",options:["20%","25%","40%","75%"],answer:1,explanation:"$50/200\\\\times100=25\\\\%$."},
      {type:"matching",marks:2,prompt:"Match each situation to its main energy store.",left:["Moving bicycle","Raised weight","Compressed spring","Battery"],options:["Kinetic","Gravitational potential","Elastic potential","Chemical"],answer:[0,1,2,3],explanation:"Each situation is associated with the named store."},
      {type:"multi",marks:2,prompt:"Select all renewable energy resources.",options:["Solar","Coal","Wind","Natural gas","Hydroelectric"],answers:[0,2,4],explanation:"Solar, wind and hydroelectric resources are naturally replenished."},
      {type:"mc",marks:1,prompt:"Which transfer is the useful output of an electric fan?",options:["Electrical","Kinetic","Chemical","Nuclear"],answer:1,explanation:"The intended useful output is kinetic energy of moving air."}
    ]},
    { kind:"completion", steps:[{key:"energyExplorer",label:"Used the energy explorer"},{key:"classify",label:"Completed the energy-store activity"},{key:"practice",label:"Completed the practice questions"}], requireQuizPass:true }
  ]
};
