import type { LessonContent } from "@/lib/lesson-content-types";

export const solidsLiquidsGasesAndDensity: LessonContent = {
  subjectSlug: "physics",
  chapterSlug: "matter-and-density",
  lessonSlug: "solids-liquids-gases-and-density",
  title: "Solids, Liquids, Gases and Density",
  objectives: [
    "Use the particle model to compare solids, liquids and gases",
    "Explain changes of state using particle energy and arrangement",
    "Calculate density, mass and volume using the density formula",
    "Describe how to measure the density of regular and irregular objects",
    "Predict floating and sinking by comparing average densities",
    "Apply matter and density ideas to everyday situations",
  ],
  sections: [
    {
      kind: "overview",
      paragraphs: [
        "Everything you can touch, breathe or pour is made of matter. Matter has mass and occupies space. Ice, liquid water and water vapour are the same substance, but their particles are arranged and move differently.",
        "Density connects mass and volume. It explains why a small metal bolt can feel heavier than a much larger piece of foam and why some objects float while others sink.",
      ],
    },
    {
      kind: "callout",
      variant: "definition",
      title: "Matter",
      body: "Matter is anything that has mass and occupies space. The particle model describes matter as tiny particles in continuous motion.",
    },
    {
      kind: "theory",
      heading: "The particle model",
      paragraphs: [
        "The particle model is a simplified scientific model. It helps us explain observable properties by thinking about particle spacing, arrangement, attraction and movement.",
        "Particles are far too small to see directly in an ordinary classroom. The circles in diagrams are models, not photographs, and the empty-looking spaces are greatly enlarged.",
      ],
      list: [
        "All matter is made of particles.",
        "Particles are always moving, even in a solid.",
        "Heating usually increases the average kinetic energy of particles.",
        "Attractive forces act between particles and are more influential when particles are close together.",
      ],
    },
    {
      kind: "table",
      heading: "Comparing the three common states",
      headers: ["Property", "Solid", "Liquid", "Gas"],
      rows: [
        ["Particle arrangement", "Closely packed and ordered", "Close together but irregular", "Far apart and random"],
        ["Particle movement", "Vibrate about fixed positions", "Move and slide past one another", "Move rapidly in all directions"],
        ["Shape", "Fixed", "Takes the container's shape", "Fills the whole container"],
        ["Volume", "Nearly fixed", "Nearly fixed", "Not fixed"],
        ["Compressibility", "Very difficult to compress", "Very difficult to compress", "Easy to compress"],
        ["Relative density", "Usually high", "Usually medium to high", "Usually very low"],
      ],
    },
    {
      kind: "cards",
      heading: "State-by-state picture",
      columns: 3,
      items: [
        { title: "Solid", icon: "box", text: "Strong attractions hold particles close to fixed positions. A solid keeps its shape." },
        { title: "Liquid", icon: "droplets", text: "Particles stay close but can rearrange, so a liquid flows and takes the shape of its container." },
        { title: "Gas", icon: "wind", text: "Particles are widely spaced and move freely, so a gas expands to fill available space." },
      ],
    },
    {
      kind: "densityExplorer",
      heading: "Interactive particle and density explorer",
    },
    {
      kind: "classifyActivity",
      heading: "Activity — Identify the state of matter",
      categories: ["Solid", "Liquid", "Gas"],
      stepKey: "statesClassify",
      items: [
        { term: "Keeps a fixed shape", category: "Solid" },
        { term: "Fills the entire container", category: "Gas" },
        { term: "Flows but keeps almost the same volume", category: "Liquid" },
        { term: "Particles vibrate about fixed positions", category: "Solid" },
        { term: "Particles are far apart", category: "Gas" },
        { term: "Particles slide past one another", category: "Liquid" },
      ],
    },
    {
      kind: "theory",
      heading: "Changes of state",
      paragraphs: [
        "A substance changes state when energy is transferred. During a change of state, the substance remains the same chemical substance; only particle arrangement and movement change.",
        "Heating can weaken the effect of attractive forces because particles gain energy. Cooling removes energy and allows attractions to hold particles more closely.",
      ],
    },
    {
      kind: "table",
      heading: "Names of changes of state",
      headers: ["Change", "From", "To", "Energy transfer"],
      rows: [
        ["Melting", "Solid", "Liquid", "Energy transferred to the substance"],
        ["Freezing", "Liquid", "Solid", "Energy transferred from the substance"],
        ["Boiling / evaporation", "Liquid", "Gas", "Energy transferred to the substance"],
        ["Condensation", "Gas", "Liquid", "Energy transferred from the substance"],
        ["Sublimation", "Solid", "Gas", "Energy transferred to the substance"],
        ["Deposition", "Gas", "Solid", "Energy transferred from the substance"],
      ],
    },
    {
      kind: "comparison",
      heading: "Evaporation and boiling",
      left: {
        title: "Evaporation",
        items: [
          "Occurs at the surface",
          "Can occur below the boiling point",
          "Faster particles escape first",
          "Often causes cooling",
        ],
      },
      right: {
        title: "Boiling",
        items: [
          "Occurs throughout the liquid",
          "Occurs at the boiling point for a given pressure",
          "Bubbles form inside the liquid",
          "Temperature stays approximately constant during the change",
        ],
      },
    },
    {
      kind: "callout",
      variant: "remember",
      title: "Temperature during a state change",
      body: "For a pure substance at constant pressure, temperature stays approximately constant while melting or boiling. The transferred energy changes particle arrangement rather than raising temperature.",
    },
    {
      kind: "theory",
      heading: "Density",
      paragraphs: [
        "Density tells us how much mass is packed into each unit of volume. A material is dense when a given volume contains a large mass.",
        "Density is a property of a material under stated conditions. Changing the size of a sample changes its mass and volume together, but normally does not change the material's density.",
      ],
    },
    {
      kind: "formula",
      latex: "\\rho=\\frac{m}{V}",
      caption: "$\\rho$ is density, $m$ is mass and $V$ is volume",
    },
    {
      kind: "table",
      heading: "Common density units",
      headers: ["Mass unit", "Volume unit", "Density unit", "Typical use"],
      rows: [
        ["kilogram (kg)", "cubic metre (m³)", "kg/m³", "SI calculations and large objects"],
        ["gram (g)", "cubic centimetre (cm³)", "g/cm³", "Small laboratory samples"],
      ],
      note: "$1\\text{ g/cm}^3 = 1000\\text{ kg/m}^3$.",
    },
    {
      kind: "example",
      prompt: "Example 1 — A block has a mass of 540 g and a volume of 200 cm³. Calculate its density.",
      steps: [
        "Write the formula: $\\rho=m/V$.",
        "Check units: mass is in grams and volume is in cubic centimetres, so the answer will be in g/cm³.",
        "Substitute: $\\rho=540/200$.",
        "Calculate: $\\rho=2.70$ g/cm³.",
        "Reasonableness check: the mass is more than twice the volume number, so a density above 2 g/cm³ is sensible.",
      ],
      answer: "Density = 2.70 g/cm³.",
    },
    {
      kind: "example",
      prompt: "Example 2 — A liquid has density 0.80 g/cm³ and volume 350 cm³. Find its mass.",
      steps: [
        "Start with $\\rho=m/V$.",
        "Rearrange by multiplying both sides by $V$: $m=\\rho V$.",
        "Substitute: $m=0.80\\times350$.",
        "Calculate: $m=280$ g.",
        "Check: a density below 1 g/cm³ means the mass number should be smaller than the volume number in these units.",
      ],
      answer: "Mass = 280 g.",
    },
    {
      kind: "example",
      prompt: "Example 3 — A metal sample has mass 780 g and density 7.8 g/cm³. Find its volume.",
      steps: [
        "Start with $\\rho=m/V$.",
        "Rearrange: $V=m/\\rho$.",
        "Substitute: $V=780/7.8$.",
        "Calculate: $V=100$ cm³.",
        "Check by multiplying density by volume: $7.8\\times100=780$ g.",
      ],
      answer: "Volume = 100 cm³.",
    },
    {
      kind: "theory",
      heading: "Measuring the density of a regular solid",
      paragraphs: [
        "Measure mass with a balance. Measure the object's dimensions with a ruler or calliper, calculate volume using the correct geometric formula, then divide mass by volume.",
      ],
      list: [
        "Rectangular block: $V=lwh$",
        "Cylinder: $V=\\pi r^2h$",
        "Cube: $V=a^3$",
        "Use consistent units before calculating density.",
      ],
    },
    {
      kind: "example",
      prompt: "Example 4 — A rectangular block is 5.0 cm long, 4.0 cm wide and 3.0 cm high. Its mass is 240 g. Find its density.",
      steps: [
        "Calculate volume: $V=lwh$.",
        "$V=5.0\\times4.0\\times3.0=60$ cm³.",
        "Use $\\rho=m/V$.",
        "$\\rho=240/60=4.0$ g/cm³.",
      ],
      answer: "Density = 4.0 g/cm³.",
    },
    {
      kind: "example",
      prompt: "Example 5 — A solid cylinder has radius 2.0 cm, height 10 cm and mass 377 g. Use $\\pi=3.14$ to find its density.",
      steps: [
        "Calculate volume: $V=\\pi r^2h$.",
        "$V=3.14\\times2.0^2\\times10=125.6$ cm³.",
        "Use $\\rho=m/V$.",
        "$\\rho=377/125.6=3.00$ g/cm³ to three significant figures.",
      ],
      answer: "Density ≈ 3.00 g/cm³.",
    },
    {
      kind: "theory",
      heading: "Measuring the density of an irregular solid",
      paragraphs: [
        "An irregular solid may not have a simple geometric volume formula. Use water displacement: record the initial water volume, fully submerge the object, record the final volume, and subtract.",
        "The object must fit inside the measuring cylinder, be fully submerged and not dissolve or react with water. Remove trapped air bubbles because they make the measured volume too large.",
      ],
    },
    {
      kind: "example",
      prompt: "Example 6 — Water rises from 45 cm³ to 73 cm³ when a stone of mass 70 g is submerged. Calculate the stone's density.",
      steps: [
        "Find displaced volume: $V=73-45=28$ cm³.",
        "Use $\\rho=m/V$.",
        "$\\rho=70/28=2.5$ g/cm³.",
      ],
      answer: "Density = 2.5 g/cm³.",
    },
    {
      kind: "theory",
      heading: "Floating and sinking",
      paragraphs: [
        "An object placed in a fluid experiences an upward buoyant force. At this level, a useful prediction is made by comparing average density with the fluid density.",
        "If the object's average density is less than the fluid density, it can float. If it is greater, it sinks. If the densities are equal, it may remain suspended when fully submerged.",
      ],
      list: [
        "Average object density < fluid density: floats",
        "Average object density = fluid density: neutral / suspended",
        "Average object density > fluid density: sinks",
      ],
    },
    {
      kind: "example",
      prompt: "Example 7 — A sealed object has mass 600 g and external volume 800 cm³. Predict what happens in water of density 1.0 g/cm³.",
      steps: [
        "Calculate average density: $\\rho=600/800=0.75$ g/cm³.",
        "Compare with water: $0.75<1.0$ g/cm³.",
        "The object's average density is lower than water's density.",
      ],
      answer: "The object floats in water.",
    },
    {
      kind: "example",
      prompt: "Example 8 — A plastic cube has mass 96 g and side length 4.0 cm. Will it float in water?",
      steps: [
        "Calculate volume: $V=4.0^3=64$ cm³.",
        "Calculate density: $\\rho=96/64=1.5$ g/cm³.",
        "Compare with water: $1.5>1.0$ g/cm³.",
      ],
      answer: "The cube sinks because its average density is greater than water's density.",
    },
    {
      kind: "example",
      prompt: "Example 9 — A hollow steel ship has a total mass of 4.0×10⁶ kg and encloses an external volume of 5.0×10³ m³. Find its average density and explain why it can float in seawater of density 1025 kg/m³.",
      steps: [
        "Use average density: $\\rho=m/V$.",
        "$\\rho=(4.0\\times10^6)/(5.0\\times10^3)=800$ kg/m³.",
        "Compare: $800<1025$ kg/m³.",
        "The hollow spaces increase external volume without adding the same proportion of mass.",
      ],
      answer: "Average density = 800 kg/m³, so the ship can float in seawater.",
    },
    {
      kind: "theory",
      heading: "Temperature, expansion and density",
      paragraphs: [
        "Most substances expand when heated. Their mass stays the same while volume increases, so density decreases. Gases show a particularly large density change when temperature or pressure changes.",
        "Water has unusual behaviour near freezing, and ice is less dense than liquid water. This is why ice floats.",
      ],
    },
    {
      kind: "example",
      prompt: "Example 10 — A gas sample has mass 1.2 kg and volume 1.0 m³. After heating at suitable conditions, its volume becomes 1.5 m³ while mass remains unchanged. Compare the densities.",
      steps: [
        "Initial density: $\\rho_1=1.2/1.0=1.2$ kg/m³.",
        "Final density: $\\rho_2=1.2/1.5=0.80$ kg/m³.",
        "The mass is unchanged but volume has increased.",
      ],
      answer: "Density decreases from 1.2 kg/m³ to 0.80 kg/m³.",
    },
    {
      kind: "realWorld",
      heading: "Matter and density in everyday life",
      items: [
        { area: "Ships", text: "A hollow hull gives a large external volume and lowers the ship's average density." },
        { area: "Hot-air balloons", text: "Heating air lowers its density compared with the cooler surrounding air." },
        { area: "Refrigeration", text: "Changes of state transfer large amounts of energy in cooling systems." },
        { area: "Material testing", text: "Measured density can help identify an unknown material or reveal internal voids." },
        { area: "Weather", text: "Differences in air density contribute to convection and atmospheric motion." },
        { area: "Cooking", text: "Evaporation, boiling, freezing and melting all involve particle-energy changes." },
      ],
    },
    {
      kind: "mistakes",
      items: [
        { wrong: "Saying particles expand when matter is heated.", right: "The particles themselves are usually modelled as unchanged; their average separation increases." },
        { wrong: "Using mass instead of density to decide floating.", right: "Compare average density with the fluid density. Very massive ships can float." },
        { wrong: "Dividing volume by mass.", right: "Density is mass divided by volume: $\\rho=m/V$." },
        { wrong: "Mixing grams with cubic metres.", right: "Use a compatible pair such as g with cm³ or kg with m³." },
        { wrong: "Using the final cylinder reading as object volume.", right: "Object volume is final reading minus initial reading." },
        { wrong: "Thinking temperature must rise during boiling.", right: "For a pure substance at constant pressure, temperature stays approximately constant during the state change." },
      ],
    },

    {
      kind: "practice",
      heading: "Self-study: Particle model — 10 questions",
      stepKey: "selfStudyParticle",
      questions: [
        { prompt: "Which statement best describes particles in a solid?", options: ["Far apart and stationary", "Closely packed and vibrating", "Close together and freely escaping", "No particles are present"], answer: 1, explanation: "Solid particles are close together and vibrate about fixed positions." },
        { prompt: "Why can a liquid flow?", options: ["Its particles can move past one another", "It has no particle attractions", "Its particles are fixed", "Its particles have zero mass"], answer: 0, explanation: "Liquid particles remain close but can change neighbours and slide past each other." },
        { prompt: "Which state is easiest to compress?", options: ["Solid", "Liquid", "Gas", "All equally"], answer: 2, explanation: "Large spaces between gas particles allow significant compression." },
        { prompt: "A gas fills its container because its particles...", options: ["are fixed in a lattice", "move freely in all directions", "have no energy", "are larger than liquid particles"], answer: 1, explanation: "Gas particles move freely and spread through the available volume." },
        { prompt: "What happens to average particle kinetic energy when temperature increases?", options: ["It usually increases", "It becomes zero", "It always decreases", "It is unrelated to temperature"], answer: 0, explanation: "Higher temperature corresponds to greater average particle kinetic energy." },
        { prompt: "Which property do both solids and liquids usually share?", options: ["They fill the whole container", "They are easily compressed", "They have nearly fixed volume", "Their particles are very far apart"], answer: 2, explanation: "Solids and liquids normally have nearly fixed volume." },
        { prompt: "In the particle model, spaces in diagrams are...", options: ["drawn exactly to scale", "usually greatly enlarged", "proof matter is mostly air", "chemical bonds"], answer: 1, explanation: "Particle diagrams are simplified and not drawn to true scale." },
        { prompt: "Which state has no fixed shape but a nearly fixed volume?", options: ["Solid", "Liquid", "Gas", "Vacuum"], answer: 1, explanation: "A liquid takes its container's shape but keeps nearly the same volume." },
        { prompt: "Particles in a solid are completely motionless. Is this correct?", options: ["Yes", "No, they vibrate", "Only above 100°C", "Only metals vibrate"], answer: 1, explanation: "Particles in a solid vibrate around fixed positions." },
        { prompt: "Which change best represents gas compression?", options: ["Particle size decreases", "Particles are pushed closer together", "Particles disappear", "Mass must increase"], answer: 1, explanation: "Compression decreases average separation; it does not normally change particle size." },
      ],
    },
    {
      kind: "practice",
      heading: "Self-study: Density and measurement — 10 questions",
      stepKey: "selfStudyDensity",
      questions: [
        { prompt: "A sample has mass 200 g and volume 50 cm³. Its density is...", options: ["0.25 g/cm³", "4 g/cm³", "150 g/cm³", "250 g/cm³"], answer: 1, explanation: "$\\rho=200/50=4$ g/cm³." },
        { prompt: "Which equation gives mass?", options: ["$m=\\rho V$", "$m=V/\\rho$", "$m=\\rho/V$", "$m=1/(\\rho V)$"], answer: 0, explanation: "Rearranging $\\rho=m/V$ gives $m=\\rho V$." },
        { prompt: "A liquid has density 1.2 g/cm³ and volume 100 cm³. Find mass.", options: ["12 g", "83.3 g", "101.2 g", "120 g"], answer: 3, explanation: "$m=1.2\\times100=120$ g." },
        { prompt: "A 360 g object has density 3 g/cm³. Find volume.", options: ["1080 cm³", "120 cm³", "363 cm³", "0.0083 cm³"], answer: 1, explanation: "$V=m/\\rho=360/3=120$ cm³." },
        { prompt: "Water rises from 60 cm³ to 85 cm³. What is the submerged object's volume?", options: ["25 cm³", "60 cm³", "85 cm³", "145 cm³"], answer: 0, explanation: "Displaced volume is $85-60=25$ cm³." },
        { prompt: "Which instrument directly measures mass?", options: ["Measuring cylinder", "Balance", "Thermometer", "Stopwatch"], answer: 1, explanation: "A balance measures mass." },
        { prompt: "A cube has side 3 cm. What is its volume?", options: ["9 cm³", "12 cm³", "18 cm³", "27 cm³"], answer: 3, explanation: "$V=3^3=27$ cm³." },
        { prompt: "Which is equivalent to 1 g/cm³?", options: ["1 kg/m³", "10 kg/m³", "100 kg/m³", "1000 kg/m³"], answer: 3, explanation: "$1$ g/cm³ equals $1000$ kg/m³." },
        { prompt: "Air bubbles stuck to an irregular object make its displacement volume...", options: ["too large", "too small", "unchanged", "negative"], answer: 0, explanation: "Trapped air also displaces water, so measured volume is too large." },
        { prompt: "Two blocks are made from the same uniform material. One is twice as large. Its density is...", options: ["twice as large", "half as large", "the same", "zero"], answer: 2, explanation: "Mass and volume increase in the same proportion, so density is unchanged." },
      ],
    },
    {
      kind: "practice",
      heading: "Self-study: Floating and sinking — 10 questions",
      stepKey: "selfStudyFloat",
      questions: [
        { prompt: "An object of density 0.80 g/cm³ is placed in water. It will usually...", options: ["float", "sink", "turn into gas", "lose all mass"], answer: 0, explanation: "Its average density is lower than water's density." },
        { prompt: "An object has density 1.30 g/cm³ in water. It will usually...", options: ["float", "sink", "remain above the water without contact", "boil"], answer: 1, explanation: "Its density is greater than water's density." },
        { prompt: "Why can a steel ship float?", options: ["Steel has no mass", "Its hollow shape lowers average density", "Seawater has zero density", "Gravity does not act at sea"], answer: 1, explanation: "The large air-filled volume makes the ship's overall average density lower than the water's." },
        { prompt: "A sealed box has mass 400 g and volume 500 cm³. Its average density is...", options: ["0.8 g/cm³", "1.25 g/cm³", "100 g/cm³", "900 g/cm³"], answer: 0, explanation: "$400/500=0.8$ g/cm³." },
        { prompt: "The box in the previous question is placed in water. It will...", options: ["float", "sink", "have no buoyant force", "become denser than steel"], answer: 0, explanation: "$0.8<1.0$ g/cm³, so it floats." },
        { prompt: "An object has exactly the same average density as a fluid and is fully submerged. It may...", options: ["remain suspended", "always fly upward", "always fall instantly", "lose volume"], answer: 0, explanation: "Equal density can produce neutral buoyancy." },
        { prompt: "Which change can help a clay ball float?", options: ["Shape it into a hollow boat", "Compress it into a smaller solid ball", "Add metal", "Remove all external volume"], answer: 0, explanation: "A hollow shape increases displaced volume and lowers average density." },
        { prompt: "Oil of density 0.85 g/cm³ is poured onto water. It forms the upper layer because...", options: ["oil is denser", "oil is less dense", "water has no mass", "density is irrelevant"], answer: 1, explanation: "The less-dense liquid forms the upper layer when the liquids do not mix." },
        { prompt: "A hot-air balloon rises mainly because heated air is...", options: ["more dense", "less dense", "solid", "without particles"], answer: 1, explanation: "Heating expands the air and lowers its density relative to surrounding air." },
        { prompt: "Which value should be compared to fluid density?", options: ["Object colour", "Object average density", "Object temperature only", "Object price"], answer: 1, explanation: "Average density provides the basic floating or sinking prediction." },
      ],
    },
    {
      kind: "practice",
      heading: "Self-study: Changes of state — 10 questions",
      stepKey: "selfStudyChanges",
      questions: [
        { prompt: "The change from solid to liquid is...", options: ["freezing", "melting", "condensation", "deposition"], answer: 1, explanation: "Melting changes a solid into a liquid." },
        { prompt: "The change from gas to liquid is...", options: ["evaporation", "sublimation", "condensation", "melting"], answer: 2, explanation: "Condensation occurs when gas particles lose energy and form a liquid." },
        { prompt: "Sublimation is a change from...", options: ["solid directly to gas", "gas directly to liquid", "liquid to solid", "gas to plasma only"], answer: 0, explanation: "Sublimation bypasses the liquid state." },
        { prompt: "Evaporation occurs...", options: ["only at the boiling point", "at the liquid surface", "only throughout the liquid", "only below 0°C"], answer: 1, explanation: "Evaporation is a surface process and can occur below boiling point." },
        { prompt: "Boiling differs from evaporation because boiling...", options: ["occurs throughout the liquid", "never forms gas", "always cools a liquid below freezing", "requires no energy"], answer: 0, explanation: "Bubbles form throughout a boiling liquid." },
        { prompt: "During melting of a pure substance at constant pressure, temperature usually...", options: ["stays approximately constant", "rises rapidly throughout", "falls to absolute zero", "becomes undefined"], answer: 0, explanation: "Transferred energy changes particle arrangement during the state change." },
        { prompt: "Freezing involves energy being transferred...", options: ["to the substance", "from the substance", "from mass to volume", "into new particles"], answer: 1, explanation: "The substance loses energy as particles become more ordered." },
        { prompt: "Why does evaporation often cause cooling?", options: ["Higher-energy particles escape", "All particles stop", "The liquid gains mass", "Density becomes infinite"], answer: 0, explanation: "Faster particles escape, reducing the average kinetic energy of particles left behind." },
        { prompt: "Water droplets on the outside of a cold glass mainly come from...", options: ["water passing through glass", "condensation of water vapour", "melting glass", "sublimation of ice inside"], answer: 1, explanation: "Water vapour in the air cools and condenses on the surface." },
        { prompt: "Which pair are reverse processes?", options: ["melting and freezing", "melting and boiling", "evaporation and sublimation", "density and volume"], answer: 0, explanation: "Melting changes solid to liquid; freezing changes liquid to solid." },
      ],
    },
    {
      kind: "summary",
      points: [
        "Solids, liquids and gases differ in particle arrangement, movement, shape and compressibility.",
        "Changes of state involve energy transfer but do not create a new chemical substance.",
        "Density is mass per unit volume: $\\rho=m/V$.",
        "Rearrangements are $m=\\rho V$ and $V=m/\\rho$.",
        "Regular-solid volume comes from dimensions; irregular-solid volume can be found by displacement.",
        "Comparing average object density with fluid density predicts floating and sinking.",
        "Heating usually increases volume and lowers density when mass stays constant.",
      ],
    },
    {
      kind: "gradedQuiz",
      heading: "Lesson Quiz: Solids, Liquids, Gases and Density",
      passMark: 60,
      questions: [
        { type: "mc", marks: 1, prompt: "Which statement describes a liquid?", options: ["Fixed shape and fixed volume", "No fixed shape but nearly fixed volume", "Fills all available space and has fixed volume", "Particles are motionless"], answer: 1, explanation: "A liquid flows to take the container's shape while retaining nearly the same volume." },
        { type: "mc", marks: 1, prompt: "Which state is most easily compressed?", options: ["Solid", "Liquid", "Gas", "All equally"], answer: 2, explanation: "Gas particles have large spaces between them." },
        { type: "mc", marks: 2, prompt: "A sample has mass 450 g and volume 150 cm³. Find density.", options: ["0.33 g/cm³", "3.0 g/cm³", "300 g/cm³", "600 g/cm³"], answer: 1, explanation: "$\\rho=450/150=3.0$ g/cm³." },
        { type: "mc", marks: 2, prompt: "A liquid has density 0.75 g/cm³ and volume 240 cm³. Find mass.", options: ["180 g", "240.75 g", "320 g", "0.0031 g"], answer: 0, explanation: "$m=\\rho V=0.75\\times240=180$ g." },
        { type: "mc", marks: 2, prompt: "Water rises from 32 cm³ to 57 cm³ when a 75 g stone is submerged. Find density.", options: ["1.32 g/cm³", "2.34 g/cm³", "3.0 g/cm³", "4.3 g/cm³"], answer: 2, explanation: "Volume is $57-32=25$ cm³, so density is $75/25=3.0$ g/cm³." },
        { type: "tf", marks: 1, prompt: "During boiling, a pure liquid's temperature normally continues rising rapidly while it changes state at constant pressure.", answer: false, explanation: "Temperature stays approximately constant during the change of state." },
        { type: "matching", marks: 3, prompt: "Match each change of state.", left: ["Solid → liquid", "Liquid → gas", "Gas → liquid", "Gas → solid", "Liquid → solid", "Solid → gas"], options: ["Melting", "Evaporation/boiling", "Condensation", "Deposition", "Freezing", "Sublimation"], answer: [0, 1, 2, 3, 4, 5], explanation: "These are the standard names for the six changes of state." },
        { type: "mc", marks: 1, prompt: "An object of average density 0.92 g/cm³ is placed in water. What is the best prediction?", options: ["It floats", "It sinks", "It must dissolve", "It becomes a gas"], answer: 0, explanation: "Its density is lower than water's density." },
        { type: "multi", marks: 2, prompt: "Select all correct statements about measuring an irregular solid's density.", options: ["Measure mass with a balance", "Use final cylinder reading alone as volume", "Subtract initial water level from final level", "Remove trapped air bubbles", "Mix kg with cm³ without conversion"], answers: [0, 2, 3], explanation: "Mass is measured with a balance and displacement is the change in water volume; bubbles should be removed." },
        { type: "mc", marks: 2, prompt: "A cube has side 5 cm and mass 500 g. What is its density?", options: ["0.25 g/cm³", "4.0 g/cm³", "20 g/cm³", "100 g/cm³"], answer: 1, explanation: "Volume is $5^3=125$ cm³ and density is $500/125=4.0$ g/cm³." },
      ],
    },
    {
      kind: "completion",
      steps: [
        { key: "densityExplorer", label: "Used the particle and density explorer" },
        { key: "statesClassify", label: "Completed the states classification activity" },
        { key: "selfStudyParticle", label: "Answered all 10 particle-model self-study questions" },
        { key: "selfStudyDensity", label: "Answered all 10 density self-study questions" },
        { key: "selfStudyFloat", label: "Answered all 10 floating and sinking self-study questions" },
        { key: "selfStudyChanges", label: "Answered all 10 changes-of-state self-study questions" },
      ],
      requireQuizPass: true,
    },
  ],
};
