import type { LessonContent } from "@/lib/lesson-content-types";

export const typesOfForces: LessonContent = {
  subjectSlug: "physics",
  chapterSlug: "forces-basics",
  lessonSlug: "types-of-forces",
  title: "Types of Forces",
  objectives: [
    "Define force and state its SI unit",
    "Distinguish contact forces from non-contact forces",
    "Describe friction, drag, tension, normal force, gravity and magnetic force",
    "Distinguish mass from weight",
    "Calculate weight using W = mg",
    "Determine resultant force and identify balanced and unbalanced forces",
  ],
  sections: [
    { kind: "overview", paragraphs: [
      "Opening a door, kicking a football, pulling a suitcase and dropping a pen all involve forces. A force can start motion, stop motion, change speed, change direction or change an object's shape.",
      "Forces are vectors, so a complete force description needs both magnitude and direction. The SI unit of force is the newton, symbol N.",
    ]},
    { kind: "callout", variant: "definition", title: "Force", body: "A force is a push or pull that can change an object's motion or shape. Force is measured in newtons (N)." },
    { kind: "theory", heading: "Effects of a force", paragraphs: [
      "A single force or an unbalanced group of forces can change velocity. This may mean starting or stopping, speeding up or slowing down, or changing direction.",
      "Forces can also deform objects. Stretching a spring, compressing a sponge and bending a ruler are examples of shape changes caused by force.",
    ], list: ["Start or stop motion", "Change speed", "Change direction", "Rotate an object", "Stretch, compress or bend an object"] },
    { kind: "theory", heading: "Contact and non-contact forces", paragraphs: [
      "Contact forces act only when objects touch. Examples include friction, drag, tension, the normal contact force, an applied push and spring force.",
      "Non-contact forces act across a distance. Gravity, magnetic force and electrostatic force can act even when objects are not touching.",
    ]},
    { kind: "comparison", heading: "Two broad groups of forces", left: { title: "Contact forces", items: ["Friction between surfaces", "Air resistance or drag", "Tension in a rope", "Normal force from a surface", "Applied push or pull", "Spring force"] }, right: { title: "Non-contact forces", items: ["Gravitational force", "Magnetic force", "Electrostatic force", "Can act through empty space"] } },
    { kind: "cards", heading: "Common forces around us", columns: 3, items: [
      { title: "Friction", icon: "grip", text: "Acts between touching surfaces and opposes relative motion or attempted motion." },
      { title: "Drag", icon: "wind", text: "A resistive force from a fluid such as air or water." },
      { title: "Tension", icon: "move-horizontal", text: "A pulling force transmitted through a taut rope, string or cable." },
      { title: "Normal force", icon: "arrow-up", text: "A support force from a surface, acting perpendicular to that surface." },
      { title: "Weight", icon: "arrow-down", text: "The gravitational force acting on a mass." },
      { title: "Magnetic force", icon: "magnet", text: "Attraction or repulsion caused by magnets or magnetic materials." },
    ]},
    { kind: "theory", heading: "Friction and drag", paragraphs: [
      "Friction acts parallel to the contact surface and opposes sliding or the tendency to slide. It is useful for walking, braking and gripping, but it can also cause heating and wear.",
      "Drag acts when an object moves through a fluid. Air resistance generally increases with speed and with the object's frontal area. Streamlined shapes reduce drag.",
    ]},
    { kind: "realWorld", heading: "Useful and unwanted friction", items: [
      { area: "Walking", text: "Static friction between shoes and the ground prevents slipping." },
      { area: "Vehicle brakes", text: "Friction converts kinetic energy mainly into thermal energy." },
      { area: "Machine parts", text: "Lubricants reduce friction, heating and wear." },
      { area: "Parachutes", text: "A large area creates greater air resistance and reduces falling speed." },
    ]},
    { kind: "theory", heading: "Mass and weight are different", paragraphs: [
      "Mass is the amount of matter in an object and is measured in kilograms (kg). Mass does not change when the object moves from Earth to the Moon.",
      "Weight is the gravitational force acting on that mass. It is measured in newtons and depends on the local gravitational field strength.",
    ]},
    { kind: "formula", latex: "W=mg", caption: "$W$ = weight in N, $m$ = mass in kg, $g$ = gravitational field strength in N/kg" },
    { kind: "comparison", heading: "Mass compared with weight", left: { title: "Mass", items: ["Amount of matter", "Scalar quantity", "Measured in kilograms (kg)", "Measured with a balance", "Normally unchanged by location"] }, right: { title: "Weight", items: ["Gravitational force", "Vector directed toward the attracting body", "Measured in newtons (N)", "Measured with a newton meter", "Changes when gravitational field strength changes"] } },
    { kind: "example", prompt: "Find the weight of a 6 kg object on Earth using $g=9.8$ N/kg.", steps: ["Write $W=mg$.", "Substitute $m=6$ kg and $g=9.8$ N/kg.", "Calculate $W=6\times9.8=58.8$ N.", "The direction is downward, toward Earth."], answer: "Weight = 58.8 N downward." },
    { kind: "example", prompt: "An astronaut has a mass of 70 kg. On the Moon, $g=1.6$ N/kg. Find the astronaut's weight.", steps: ["Mass remains 70 kg.", "Use $W=mg$.", "Substitute: $W=70\times1.6$.", "Calculate $W=112$ N."], answer: "Moon weight = 112 N. The astronaut's mass is still 70 kg." },
    { kind: "theory", heading: "Balanced, unbalanced and resultant forces", paragraphs: [
      "The resultant force is the single force that has the same overall effect as all the forces acting together. Forces in the same direction add; forces in opposite directions subtract.",
      "Balanced forces have a resultant of zero. They do not change velocity: an object can remain at rest or continue moving at constant velocity. Unbalanced forces have a non-zero resultant and cause acceleration.",
    ]},
    { kind: "formula", latex: "F_{\text{resultant}}=\sum F", caption: "Choose one direction as positive and include signs consistently." },
    { kind: "example", prompt: "A box is pushed with 14 N to the right while friction acts with 6 N to the left. Find the resultant force.", steps: ["Choose right as positive.", "Subtract the opposing force: $14-6=8$ N.", "The larger force is to the right."], answer: "Resultant force = 8 N to the right." },
    { kind: "example", prompt: "A lamp hangs motionless. Its weight is 25 N downward and the cable tension is 25 N upward.", steps: ["The forces are equal in size and opposite in direction.", "Resultant force: $25-25=0$ N.", "Zero resultant means no acceleration."], answer: "The forces are balanced; resultant force = 0 N." },
    { kind: "forceExplorer", heading: "Interactive activity — Balanced and unbalanced forces" },
    { kind: "classifyActivity", heading: "Activity — Contact or non-contact?", categories: ["Contact", "Non-contact"], items: [
      { term: "Friction", category: "Contact" },
      { term: "Tension", category: "Contact" },
      { term: "Normal force", category: "Contact" },
      { term: "Air resistance", category: "Contact" },
      { term: "Gravity", category: "Non-contact" },
      { term: "Magnetic force", category: "Non-contact" },
      { term: "Electrostatic force", category: "Non-contact" },
    ]},
    { kind: "mistakes", items: [
      { wrong: "Writing mass in newtons.", right: "Mass is measured in kilograms; weight is measured in newtons." },
      { wrong: "Thinking balanced forces mean no forces act.", right: "Several forces may act, but their vector sum is zero." },
      { wrong: "Assuming a moving object must have a forward resultant force.", right: "An object can move at constant velocity with zero resultant force." },
      { wrong: "Adding opposite forces without considering direction.", right: "Choose a positive direction and subtract forces that act oppositely." },
    ]},
    { kind: "practice", heading: "Practice (not graded)", questions: [
      { prompt: "Which is a non-contact force?", options: ["Friction", "Tension", "Gravity"], answer: 2, explanation: "Gravity acts across a distance without physical contact." },
      { prompt: "A 10 N force acts right and a 4 N force acts left. What is the resultant?", options: ["14 N right", "6 N right", "6 N left"], answer: 1, explanation: "10 − 4 = 6 N toward the larger force." },
      { prompt: "What is the SI unit of force?", options: ["kilogram", "pascal", "newton"], answer: 2, explanation: "Force is measured in newtons, N." },
      { prompt: "Find the weight of a 5 kg mass when $g=10$ N/kg.", options: ["0.5 N", "50 N", "15 N"], answer: 1, explanation: "$W=mg=5\times10=50$ N." },
      { prompt: "Balanced forces cause:", options: ["Zero acceleration", "Increasing speed", "A change of direction every time"], answer: 0, explanation: "A zero resultant force produces no acceleration." },
    ]},
    { kind: "summary", points: [
      "A force is a vector push or pull measured in newtons.",
      "Contact forces require touching; non-contact forces act across a distance.",
      "Friction and drag oppose relative motion.",
      "Mass is measured in kilograms, while weight is a force measured in newtons.",
      "Use $W=mg$ to calculate weight.",
      "Balanced forces have zero resultant and cause no acceleration.",
      "Unbalanced forces produce a non-zero resultant and can change velocity.",
    ]},
    { kind: "gradedQuiz", heading: "Lesson Quiz: Types of Forces", passMark: 60, questions: [
      { type: "mc", marks: 1, prompt: "Which statement best defines a force?", options: ["A push or pull", "The amount of matter", "Distance divided by time", "Energy stored in an object"], answer: 0, explanation: "A force is a push or pull that can change motion or shape." },
      { type: "mc", marks: 1, prompt: "Which force is non-contact?", options: ["Tension", "Normal force", "Magnetic force", "Friction"], answer: 2, explanation: "Magnetic force can act without objects touching." },
      { type: "tf", marks: 1, prompt: "Balanced forces mean that no forces are acting on the object.", answer: false, explanation: "Balanced forces can be present; their vector sum is simply zero." },
      { type: "mc", marks: 2, prompt: "A 16 N force acts east and a 9 N force acts west. What is the resultant?", options: ["25 N east", "7 N east", "7 N west", "0 N"], answer: 1, explanation: "16 − 9 = 7 N toward the east." },
      { type: "mc", marks: 2, prompt: "A 4 kg object is in a gravitational field of 9.8 N/kg. What is its weight?", options: ["2.45 N", "13.8 N", "39.2 N", "40.8 N"], answer: 2, explanation: "$W=mg=4\times9.8=39.2$ N." },
      { type: "matching", marks: 2, prompt: "Match each force with its description.", left: ["Friction", "Tension", "Normal force", "Weight"], options: ["Opposes sliding between surfaces", "Pull transmitted by a rope", "Support perpendicular to a surface", "Gravitational force on a mass"], answer: [0,1,2,3], explanation: "Each description identifies the physical origin and direction of the named force." },
      { type: "multi", marks: 2, prompt: "Select all contact forces.", options: ["Friction", "Gravity", "Air resistance", "Tension", "Magnetic force"], answers: [0,2,3], explanation: "Friction, air resistance and tension involve physical contact with matter." },
      { type: "mc", marks: 1, prompt: "An object moves at constant velocity in a straight line. What can be concluded about the resultant force?", options: ["It is zero", "It points forward", "It points backward", "It equals the object's mass"], answer: 0, explanation: "Constant velocity means zero acceleration and therefore zero resultant force." },
    ]},
    { kind: "completion", steps: [
      { key: "forceExplorer", label: "Used the balanced-force explorer" },
      { key: "classify", label: "Completed the contact/non-contact activity" },
      { key: "practice", label: "Completed the practice questions" },
    ], requireQuizPass: true },
  ],
};
