"use client";
import { useEffect,useMemo,useState } from "react";
import audit from "@/data/physics-audit.json";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
type Assignment={id:string;title:string;chapterSlug:string;lessonSlug:string;due:string;className:string;createdAt:string};
type Row={chapter:string;chapterSlug:string;title:string;slug:string};
const KEY="eduverse:teacher-assignments:v1";
export function TeacherDashboard(){const rows=audit as Row[];const chapters=useMemo(()=>[...new Map(rows.map(x=>[x.chapterSlug,x.chapter])).entries()], [rows]);const[ch,setCh]=useState(chapters[0]?.[0]??"");const[lesson,setLesson]=useState("");const[className,setClassName]=useState("Physics Class");const[due,setDue]=useState("");const[items,setItems]=useState<Assignment[]>([]);useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)??"[]"))}catch{}},[]);const lessons=rows.filter(x=>x.chapterSlug===ch);useEffect(()=>setLesson(lessons[0]?.slug??""),[ch]);function create(){const row=rows.find(x=>x.chapterSlug===ch&&x.slug===lesson);if(!row)return;const next={id:crypto.randomUUID(),title:row.title,chapterSlug:ch,lessonSlug:lesson,due,className,createdAt:new Date().toISOString()};const all=[next,...items];setItems(all);localStorage.setItem(KEY,JSON.stringify(all))}function csv(){const lines=["Class,Lesson,Chapter,Due,Assignment URL",...items.map(x=>[x.className,x.title,x.chapterSlug,x.due,`${location.origin}/subjects/physics/${x.chapterSlug}/${x.lessonSlug}`].map(v=>`"${v}"`).join(","))];const b=new Blob([lines.join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="eduverse-assignments.csv";a.click()}return <div className="space-y-8"><Card><CardHeader><CardTitle>Create Physics assignment</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><input className="rounded-md border p-2" value={className} onChange={e=>setClassName(e.target.value)} placeholder="Class name"/><input className="rounded-md border p-2" type="date" value={due} onChange={e=>setDue(e.target.value)}/><select className="rounded-md border p-2" value={ch} onChange={e=>setCh(e.target.value)}>{chapters.map(([slug,title])=><option key={slug} value={slug}>{title}</option>)}</select><select className="rounded-md border p-2" value={lesson} onChange={e=>setLesson(e.target.value)}>{lessons.map(x=><option key={x.slug} value={x.slug}>{x.title}</option>)}</select><Button onClick={create}>Create assignment</Button><Button variant="outline" onClick={csv} disabled={!items.length}>Export CSV</Button></CardContent></Card><div className="grid gap-4">{items.map(x=><Card key={x.id}><CardContent className="flex items-center justify-between gap-4 pt-6"><div><p className="font-semibold">{x.title}</p><p className="text-sm text-muted-foreground">{x.className}{x.due?` · Due ${x.due}`:""}</p></div><Button asChild variant="outline"><a href={`/subjects/physics/${x.chapterSlug}/${x.lessonSlug}`}>Open</a></Button></CardContent></Card>)}</div></div>}
